# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodRescure' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'RxSwift', '~> 6'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxGesture'
pod 'SDWebImage', '~> 5.0'

pod 'R.swift'

  # Pods for FoodRescure

  target 'FoodRescureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodRescureUITests' do
    # Pods for testing
  end

end
